version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app_postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    image: app_movil:latest
    container_name: fastapi_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/app_postgres
    ports:
      - "8000:8000"

  frontend:
    image: nginx:alpine
    container_name: flutter_frontend
    volumes:
      - ./frontend/build/web:/usr/share/nginx/html
    ports:
      - "3000:80"

volumes:
  pgdata: